### PR TITLE
Add systemIO_power and update MQTT syntax

### PR DESCRIPTION
**Pull request by MartinJSa**
Added the new systemIO_power register and also updated the MQTT syntax as the old one stops working in the 2022.12 HA release.

### CODE REVIEW

**Comment by cmcgerty** [comment]
@MartinJSa Did you realise that the polarity of systemIO_power is opposite to battery_power? In the Node-Red flow I switched it so that the new value is a drop-in replacement for the old.

systemIO_power

**Comment by MartinJSa** [comment]
Good point, I was a bit lazy and dealt with that in the HA UI, I'll update config.yaml now

**Comment by MartinJSa** [comment]
I think I've updated the PR but I'm a bit clueless on github, can you see the change?

**Comment by cmcgerty** [comment]
I know what you mean, GitHub is a bit opaque. I never feel totally confident that I know what I'm doing. It looks fine, I'll merge it now.

**Pull request merged**
